[agents]
amp = false
claude-code = true
codex = true
factory = false
opencode = false

[dependencies.superpowers]
marketplace = "obra/superpowers-marketplace"
plugin = "superpowers"
type = "claude-plugin"
