services:
	postgres:
		image: postgres:18
		container_name: skillssupply_dev
		ports:
			- "5432:5432"
		environment:
			POSTGRES_USER: postgres
			POSTGRES_PASSWORD: postgres
			POSTGRES_DB: skillssupply_dev
		volumes:
			- skillssupply_dev:/var/lib/postgresql/data

volumes:
	skillssupply_dev:
